### ISSUE TITLE
Refactor into standalone plugin

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/nvim-treesitter-textobjects#503]
[Nvim-treesitter 1.0](https://github.com/nvim-treesitter/nvim-treesitter/issues/4767) (expected later this year) will completely remove the module system in order to significantly reduce complexity.

This means that nvim-treesitter-textobjects needs to be refactored into a standalone plugin, similarly to https://github.com/nvim-treesitter/nvim-treesitter-context or the [`indent.lua` module in 1.0](https://github.com/nvim-treesitter/nvim-treesitter/blob/main/lua/nvim-treesitter/indent.lua). (There's no need to hook into `nvim-treesitter`; textobjects should simply work if a suitable parser and queries are in runtimepath. This should also allow simplifying the `setup` as it no longer needs to be shoehorned into the nvim-treesitter setup structure.)

As a bonus, the `incremental-selection` (also removed in 1.0) feature could be integrated here as a `in`/`an` node object.

**Comment by TheLeoP** [comment]
Would a PR be welcome?

**Comment by clason** [comment]
Of course!

**Comment by TheLeoP** [comment]
Would the PR also have to remove the dependency on nvim-treesitter?

**Comment by clason** [comment]
Yes, that is the whole point!

**Comment by ilan-schemoul** [comment]
> [Nvim-treesitter 1.0](https://github.com/nvim-treesitter/nvim-treesitter/issues/4767) (expected later this year) will completely remove the module system in order to significantly reduce complexity

For reference : nvim treesitter roadmap to 1.0 now reads we'll wait nvim 0.11 before Treesitter 1.0. nvim 0.10 just got released after a very long time and now we need to wait 0.11 then (hopefully) Treesitter will be 0.10 then (hopefully) this package will be 1.0

All this could take a year or two so I find it not a great thing my PR get halt because we have to wait 1.0 https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/588#issuecomment-2047918166

**Comment by clason** [comment]
I consider this as completed by #523 and the follow-up fixes (thanks all!). Feel free to test it (if **and only if** you are testing nvim-treesitter `main`!) and report (or, better yet, fix) any regressions you find.
