### ISSUE TITLE
Mappings not working for custom filetypes

### ISSUE THREAD

**Issue by LorNtz** [nvim-treesitter/nvim-treesitter-textobjects#668]
Just copied the example config in README and tried `vif` mapping in different file types. For files like lua or typescript it works totally fine, but not when I'm trying on a custom file type in my workflow. The file is somewhat like a vue sfc file that contains a script tag with typescript code inside, and I've written the treesitter parser and queries for the filetype on my own. I'm sure it's keymapping not taking effect since manally running `:TSTextobjectSelect @function.inner` inside a typescript function correctly selects the function body in visual mode, so the parser and queries should be fine in my understanding.
I'm using lunarvim with lazy.nvim. Here's my `config.lua` (only the relevant parts):
```lua
lvim.plugins = {
  {
    'nvim-treesitter/nvim-treesitter-textobjects'
  }
}
local ts = lvim.builtin.treesitter
ts.textobjects = {
  select = {
    enable = true,
    lookahead = true,
    keymaps = {
      ["af"] = "@function.outer",
      ["if"] = "@function.inner"
    },
  },
  swap = {
    enable = false
  },
}
```

**Comment by clason** [comment]
If the filetype is not supported by nvim-treesitter (see the list in the README), it won't work. Since you say it's custom, this is virtually guaranteed to be the case.

If you are 100% certain that the filetype is fully compatible with a supported language, you can use `vim.treesitter.language.register()` to make your filetype use the parser for that language.
